export const GET_NEW_TOKEN_SUCCESS = 'GET_NEW_TOKEN_SUCCESS'
export const FAIL_AUTH_REQUEST = 'FAIL_AUTH_REQUEST'
export const RESET_AUTH_TOKEN = 'RESET_AUTH_TOKEN'

export const GET_USER_NUMBER = 'GET_USER_NUMBER'
export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_MEM_NUMBER = 'SET_MEM_NUMBER'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const GET_ALL_CALLFLOW = 'GET_ALL_CALLFLOW'

export const GET_ALL_VOICEMAILS = 'GET_ALL_VOICEMAILS'
export const GET_ALL_HOME = 'GET_ALL_HOME'
export const SMS_NOTIFICATION = 'SMS_NOTIFICATION'

export const GET_CALL_FORWARD = 'GET_CALL_FORWARD'
