<?php


namespace Tests\Feature\Services;

use App\Classes\InstagramAPIMock;
use App\Models\SocialAccount;
use App\Models\Page;
use App\Services\Social\InstagramService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class InstagramServiceTest extends TestCase
{

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_update_user_data()
    {
        $socialAccount = SocialAccount::create(['provider_name' => 'instagram', 'provider_id' => '17841451137293887']);
        $page = Page::create(['page_id' => '17841451137293887', 'social_account_id' => $socialAccount->id]);

        $service = new InstagramService($socialAccount);
        $service->setApi(new InstagramAPIMock);
        $service->updateUserData();

        // SOCIAL ACCOUNT
        $this->assertDatabaseCount('social_accounts', 1);
        $this->assertDatabaseHas('social_accounts', [
            'full_name' => 'TerraForce Software After Update',
            'avatar' => 'https://avatar'
        ]);

        // PAGES
        $this->assertDatabaseCount('pages', 1);

        // PAGE DATA
        $this->assertDatabaseCount('page_data', 30);
        $this->assertDatabaseHas('page_data', [
            'page_id' => $page->id,
            'date' => '2022-03-22',
            'page_impressions' => 8,
            'page_reach' => 7,
            'page_views' => 6,
            'page_fans' => 5
        ]);

        // FOLLOWERS
        $this->assertDatabaseCount('page_followers', 24);
        // TODO:: check to use date because of instagram data, see resources/test/get_instagram_follower_insights.json
        $this->assertDatabaseHas('page_followers', [
            'page_id' => $page->id,
            'country' => 'UA',
            'number_followers' => 39
        ]);

        // POSTS
        $this->assertDatabaseCount('posts', 9);
        $this->assertDatabaseHas('posts', [
            'page_id' => $page->id,
            'post_id' => '17916110417271939',
            'image' => 'https://image',
            'text' => 'Ось так ми святкували Новий рiк Хмельницьким офiсом #terraforce. Щирi вiтання з прийдешнiми святами та бажаємо всього найкращого i найприємнiшого у цьому роцi! :))',
            'created_date' => '2022-01-21',
            'likes_count' => 8,
            'comments_count' => 4,
            'reach' => 25,
            'engaged' => 11,
        ]);
    }

    public function test_doubled_of_update_user_data()
    {
        $socialAccount = SocialAccount::create(['provider_name' => 'instagram', 'provider_id' => '17841451137293887']);
        $page = Page::create(['page_id' => '17841451137293887', 'social_account_id' => $socialAccount->id]);

        $service = new InstagramService($socialAccount);
        $service->setApi(new InstagramAPIMock);
        $service->updateUserData();

        // repeat data update
        $socialAccount->last_imported_at = null;
        $socialAccount->save();

        $service = new InstagramService($socialAccount);
        $service->setApi(new InstagramAPIMock);
        $service->updateUserData();

        $this->assertDatabaseCount('social_accounts', 1);
        $this->assertDatabaseCount('pages', 1);
        $this->assertDatabaseCount('page_data', 30);
        $this->assertDatabaseCount('page_followers', 24);
        $this->assertDatabaseCount('posts', 9);
    }
}
